language: csharp
mono: none
dotnet: 2.1.4
services:
  - docker
jobs:
  include:
    - stage: build and test
      script:
        - dotnet restore ./ABCBot.sln
        - dotnet build ./src/ABCBot/ABCBot.csproj
        - dotnet test ./test/ABCBot.Tests/ABCBot.Tests.csproj
    - stage: publish
      script:
        - dotnet restore ./ABCBot.sln
        - dotnet publish ./src/ABCBot/ABCBot.csproj -c Release
        - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        - docker build ./src/ABCBot/ -f ./src/ABCBot/Dockerfile -t flaez/abcbot
        - docker push flaez/abcbot